/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atmsimulationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Pinchange1 extends javax.swing.JFrame {
    private String pin;

    /**
     * Creates new form 
     */
    public Pinchange1() {
        initComponents();
    }

    Pinchange1(String pinnumber) {
        this.pin = pinnumber;
                initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pin1 = new javax.swing.JTextField();
        pin2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHANGE YOUR PIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 170, 259, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New PIN :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 250, 163, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Re-enter new PIN :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 290, 163, 30);

        pin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin1ActionPerformed(evt);
            }
        });
        getContentPane().add(pin1);
        pin1.setBounds(540, 250, 177, 30);

        pin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin2ActionPerformed(evt);
            }
        });
        getContentPane().add(pin2);
        pin2.setBounds(540, 290, 177, 30);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 330, 102, 31);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 370, 102, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmsimulationsystem/images/atm4.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 10, 1210, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin1ActionPerformed

    private void pin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Transaction(pin).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
         String pin = pin1.getText();
     String repin = pin2.getText();
     if(!pin.equals(repin)){
         JOptionPane.showMessageDialog(null,"PIN not matched");
         return;
     }
     if(pin.equals("")){
         JOptionPane.showMessageDialog(null,"Please enter new PIN");
         return;
     }
     if(repin.equals("")){
         JOptionPane.showMessageDialog(null,"Please re-enter new PIN");
         return;
     }
      DB.DBConnection db = new DB.DBConnection();
      String query1 = "update banktransaction set pin = '"+repin+"' where pin = '"+pin+"'";
            String query2 = "update application3 set pin = '"+repin+"' where pin = '"+pin+"'";    
            String query3 = "update login set pin = '"+repin+"' where pin = '"+pin+"'";
            db.st.executeUpdate(query1);
            db.st.executeUpdate(query2);
            db.st.executeUpdate(query3);
            JOptionPane.showMessageDialog(null,"PIN changed successfully");
            new Transaction(repin).setVisible(true);
            this.setVisible(false);
      

    }
    catch(Exception e){
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinchange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinchange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinchange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinchange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinchange1("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField pin1;
    private javax.swing.JTextField pin2;
    // End of variables declaration//GEN-END:variables
}
